from datetime import datetime
from pathlib import Path
import sys
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent

if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from request_for_YPI.dnssec_engine import (
    get_ccTLD_nameserver_count,
    get_ccTLD_ipv6_enablement,
    get_ccTLD_asn_diversity
)


def generate_markdown_report(country, ns_data, ipv6_data, asn_data):

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")

    report = f"""# DNSSEC Policy Brief — {country}

*Report generated by ISOC Pulse × IYP DNSSEC Policy Engine*

*Team: Rahul Rajesh, Ron Prajoth, Aditya Menon | Mentor: Amreesh Phokeer (ISOC)*

**Generated:** {timestamp}
**Data Sources:** Internet Yellow Pages (IYP) Neo4j
**Framework:** ISOC Internet Resilience Index — Security Pillar (DNS Security)

---

## Executive Summary

The .{country.lower()} ccTLD is currently served by {ns_data['nameserver_count']} authoritative nameservers.

{ipv6_data['ipv6_enabled_nameservers']} of {ipv6_data['total_nameservers']} authoritative nameservers support IPv6 connectivity, resulting in an IPv6 enablement rate of {ipv6_data['ipv6_percentage']}%.

The authoritative DNS infrastructure is distributed across {asn_data['distinct_asns']} distinct Autonomous Systems, improving resilience against network and routing failures.

---

## Section 1 — Core Infrastructure (ccTLD Health)

### 1.2 Number of Authoritative Nameservers

**ccTLD:** .{country.lower()}

**Authoritative Nameservers:** {ns_data['nameserver_count']}

| Nameserver |
|------------|
"""

    for ns in ipv6_data["nameservers"]:
        report += f"| {ns['nameserver']} |\n"

    report += f"""

---

### 1.2.1 IPv6 Enablement

**Nameservers Assessed:** {ipv6_data['total_nameservers']}

**IPv6 Enabled:** {ipv6_data['ipv6_enabled_nameservers']}

**IPv6 Enablement Rate:** {ipv6_data['ipv6_percentage']}%

| Nameserver | IPv6 Enabled |
|------------|--------------|
"""

    for ns in ipv6_data["nameservers"]:
        status = "Yes" if ns["ipv6_enabled"] else "No"
        report += f"| {ns['nameserver']} | {status} |\n"

    report += f"""

---

### 1.2.2 ASN Diversity

**Distinct Hosting ASNs:** {asn_data['distinct_asns']}

| ASN |
|-----|
"""

    for asn in asn_data["asns"]:
        report += f"| AS{asn} |\n"

    report += """

> Distribution across multiple autonomous systems improves resilience
> against ASN-specific outages, routing incidents, and infrastructure
> concentration risks.

---
"""

    return report


def main():

    if len(sys.argv) < 2:
        print("Usage: python dnssec_report.py IN")
        sys.exit(1)

    country = sys.argv[1].upper()

    print(f"Generating DNSSEC report for .{country.lower()} ...")

    ns_data = get_ccTLD_nameserver_count(country)
    ipv6_data = get_ccTLD_ipv6_enablement(country)
    asn_data = get_ccTLD_asn_diversity(country)

    report_text = generate_markdown_report(
        country,
        ns_data,
        ipv6_data,
        asn_data
    )

    reports_dir = Path("reports")
    reports_dir.mkdir(exist_ok=True)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M")

    output_file = reports_dir / f"DNSSEC_{country}_{timestamp}.md"

    with open(output_file, "w", encoding="utf-8") as f:
        f.write(report_text)

    print(f"\n✅ Report generated successfully")
    print(f"📄 {output_file.resolve()}")


if __name__ == "__main__":
    main()
