import argparse
import os
import sys
from datetime import datetime

# Ensure stdout supports UTF-8 for emojis on Windows
if sys.stdout.encoding and sys.stdout.encoding.lower() != 'utf-8':
    sys.stdout.reconfigure(encoding='utf-8')

# Add root directory to path to allow imports
import pathlib
ROOT = pathlib.Path(__file__).resolve().parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from request_for_YPI.peering_engine import build_peering_report_data

def generate_markdown_report(country, peering_data):
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")
    
    scorecard = peering_data.get("scorecard", {})
    
    # Extract components
    macro = peering_data.get("macro_network", {})
    market = peering_data.get("market_readiness", {})
    ixp_infra = peering_data.get("ixp_infrastructure", {})
    localization = peering_data.get("content_localization", {})
    routing = peering_data.get("routing_performance", {})
    
    # Nested components
    asn_landscape = macro.get("asn_landscape", {})
    ixp_activity = ixp_infra.get("ixp_activity", {})
    ixp_geo = ixp_infra.get("geographic_distribution", {})
    on_net = localization.get("onnet_caching_nodes", {})
    loc_ratio = localization.get("localization_ratio", {})
    tromb = routing.get("domestic_tromboning", {})
    latency = routing.get("edge_content_latency", {})

    report = f"""# Peering Policy Brief — {country}

*Report generated by ISOC Pulse × IYP Peering Policy Engine*
*Team: Rahul Rajesh, Ron Prajoth, Aditya Menon | Mentor: Amreesh Phokeer (ISOC)*

**Generated:** {timestamp}
**Data Sources:** PeeringDB, ISOC Pulse API, RIPE Atlas, PCH
**Framework:** ISOC Internet Resilience Index — Peering

---

## Executive Summary

The peering ecosystem for **{country}** relies on **{asn_landscape.get('routed_asns', 0)}** active autonomous systems connecting its domestic infrastructure. 
A mature peering ecosystem ensures that domestic traffic remains local, utilizing domestic Internet Exchange Points (IXPs) and local caching rather than relying on expensive international transit routes.

- **Active ASNs:** {asn_landscape.get('routed_asns', 0)}
- **Peering Efficiency Score:** {loc_ratio.get('peering_efficiency_score', 0):.4f}

---

## Section 1 & 2 — Market Readiness & IXP Infrastructure

### IXP Ecosystem
**Total Internet Exchange Points (IXPs):** {ixp_activity.get('total_ixps', 0)}
**Total Peering Facilities:** {ixp_geo.get('facility_count', 0)}

These facilities form the physical foundation for networks to exchange traffic without relying on international transit.

---

## Section 3 — On-Net Caching

### CDNs Present in Domestic Facilities
**Tier-1 CDNs Present:** {on_net.get('cdn_count', 0)}
**Major CDNs Discovered:** {', '.join([c['name'] for c in on_net.get('cdns_in_local_facilities', [])]) if on_net.get('cdns_in_local_facilities') else 'None'}

Having Tier-1 CDNs (like Google, Netflix, Akamai, Cloudflare) physically present in local data centers significantly reduces the need to fetch content internationally, boosting user experience and reducing transit costs.

---

## Section 4 — Traffic Localization

### Peering Efficiency / Localization Ratio
**Localization Ratio:** {loc_ratio.get('localization_percentage', 0):.2f}%
*(Sourced from ISOC Pulse)*

A localization ratio of {loc_ratio.get('localization_percentage', 0):.2f}% indicates the proportion of traffic that remains domestic. Higher ratios demonstrate mature local content ecosystems and well-utilized IXP infrastructure.

---

## Section 5 — Routing Efficiency

### 5.1 Domestic Tromboning
**Tromboning / Boomerang Routing:** {tromb.get('tromboning_percentage', 0):.1f}%
**Traceroutes Analyzed:** {tromb.get('domestic_paths_analyzed', 0)}

{tromb.get('tromboning_percentage', 0):.1f}% of analyzed domestic-to-domestic traffic left the country's borders before returning. This "boomerang" routing adds latency and security risks, typically indicating a lack of domestic peering agreements among ISPs.

### 5.2 Eyeball Latency to Edge Content
**Median Edge Latency:** {latency.get('median_latency_ms', 0):.2f} ms
**Probes Sampled:** {latency.get('probes_sampled', 0)}

Median latency from eyeball networks to root anycast servers provides a proxy for user experience. A latency of {latency.get('median_latency_ms', 0):.2f} ms shows the typical delay users face when accessing core infrastructure.
"""
    return report

def main():
    parser = argparse.ArgumentParser(description="Generate a Peering Report for a given country")
    parser.add_argument("country", type=str, help="Country Code (e.g. FR, IN)")
    parser.add_argument("--no-export", action="store_true", help="Do not save the markdown report")
    parser.add_argument("--html", action="store_true", help="Automatically generate HTML via LLM")
    
    args = parser.parse_args()
    country = args.country.upper()
    
    print(f"🔍 Running Peering Engine for {country}...")
    peering_data = build_peering_report_data(country)
    
    print("📝 Generating Markdown Report...")
    report_md = generate_markdown_report(country, peering_data)
    
    print("\n" + "="*60)
    print("REPORT PREVIEW:")
    print("="*60)
    print(report_md[:1000] + "\n...\n")
    
    if not args.no_export:
        os.makedirs("reports", exist_ok=True)
        report_path = os.path.join("reports", f"Peering_Report_{country}.md")
        with open(report_path, "w", encoding="utf-8") as f:
            f.write(report_md)
        print(f"✅ Markdown Report saved to {report_path}")
        
        if args.html:
            print("🤖 Calling generate_llm_brief.py to create HTML...")
            cmd = f'"{sys.executable}" generate_llm_brief.py peering {country}'
            os.system(cmd)
            
if __name__ == "__main__":
    main()
